#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    TheSkyX_Path=`/usr/bin/find /Applications -maxdepth 3 -name TheSkyX\*.app`
    if [ -d "$TheSkyX_Path" ]; then
		TheSkyX_Path="${TheSkyX_Path}/Contents"
    else
	   echo TheSkyX application was not found.
    	exit 1
	 fi
else
	TheSkyX_Path=$(<"$TheSkyX_Install")
fi

echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="PlugIns64"
else
	PLUGINS_DIR="PlugIns"
fi

echo "installing in $TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/"

mkdir -p "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/"

cp "/tmp/XagylFilterWheel_X2/filterwheellist xagyl.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
cp "/tmp/XagylFilterWheel_X2/XagylFilterWheel.ui" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/"
cp "/tmp/XagylFilterWheel_X2/Xagyl.png" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/"
cp "/tmp/XagylFilterWheel_X2/libXagylFilterWheel.dylib" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/filterwheellist xagyl.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/XagylFilterWheel.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/Xagyl.png"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/FilterWheelPlugIns/libXagylFilterWheel.dylib"
fi

rm -rf /tmp/XagylFilterWheel_X2

